#!/bin/sh
# shellcheck shell=dash source=ekuku-plugins/

ACTION="$1"
ARG1="$2"
ARG2="$3"	# empty or <debug>

usage()
{
	cat <<EOF
Usage:	$0 <action> <option1> <option2>

  e.g:	$0 fastscan /dir/to/scan <debug>

	$0 refill
	$0 table_drop
	$0 table_show
	$0 table_show_files
	$0 table_show_meta

	$0 fastscan <dir>
	$0 atomic
	$0 mimesha

	$0 test_images <dir>
	$0 show_images <dir>
	$0 mime <file>

	$0 check_deps
	$0 check_code
	$0 check

EOF
}

loop1_fastscan()	# deps: find
{
	local dir="$1"

	prepare_db
	find "$dir" -printf "$( findoutput_to_sqlcommands )\n"
}

loop2_mime_and_sha256()		# deps: test
{
	local file mime sha256

	while true; do {
		file="$( db_select_nextfile_without_mime )"
		[ -f "$file" ] || return 0

		mime="$( mimetype_get "$file" )"
		sha256="$( sha256_get "$file" )"

		# autodeletes 'queued' keyword in sha256
		db_insert_mime_and_sha256 "$file" "$mime" "$sha256"
	} done
}

json_check_or_die()	# deps: jq
{
	local file="$1"

	jq . <"$file" >/dev/null || {
		log "jq-error:$? file: $file #############"
		exit 1
	}
}

function_files_get()	# deps: find, ls
{
	ls README.md
	find "$SCRIPTDIR/ekuku-plugins" -type f
}

include_plugins()
{
	local file

	# shellcheck disable=SC1091
	for file in "$PLUGINDIR/"*; do . "$file"; done
}

SCRIPTDIR="$( CDPATH='' cd -- "$( dirname -- "$0")" && pwd )"
PLUGINDIR="$SCRIPTDIR/ekuku-plugins"
include_plugins

case "$ACTION" in
	table_drop)
		set -x
		db_query "DROP TABLE rexxbot.objects"
		db_query "DROP TABLE rexxbot.metadata"
	;;
	table_show)
		CONDITION=
		test -n "$ARG1" && CONDITION="WHERE $ARG1 = '$ARG2'"

		db_query "SELECT * FROM rexxbot.objects $CONDITION" human
		db_query "SELECT * FROM rexxbot.metadata" human
	;;
	table_show_files)
		db_query "SELECT * FROM rexxbot.objects WHERE type = 'f'" human
	;;
	table_show_meta)
		db_query "SELECT * FROM rexxbot.metadata" human
	;;
	prepare_db)
		prepare_db | pump_into_db
	;;
	fastscan)
		loop1_fastscan "${ARG1:-testdir}" | pump_into_db
	;;
	mimesha)
		loop2_mime_and_sha256
	;;
	like)
		# https://www.cybertec-postgresql.com/en/postgresql-more-performance-for-like-and-ilike-statements/
	;;
	refill)
		$0 table_drop
		$0 fastscan "${ARG1:-testdir/}"
		$0 table_show_files | wc -l
		$0 table_show_files | head -n5
		echo
		$0 table_show_meta  | head -n5
		echo

		while true; do {
			$0 atomic || break
		} done

		C1="$( db_query 'select count(distinct(sha256)) from rexxbot.objects  where sha256 is not null' )"
		C2="$( db_query 'select count(distinct(sha256)) from rexxbot.metadata where sha256 is not null' )"
		C3="$( db_query "select count(sha256) from rexxbot.metadata where data->'rc' = '1';" )"
		C4="$( db_query "select count(sha256) from rexxbot.metadata where data is null and mime like 'image/%';" )"
		C5="$( db_query "select count(sha256) from rexxbot.metadata where preview is null and mime like 'image/%';" )"
		# select data->>'colors' from metadata where data->>'colors' is not null;

		echo
		echo "unique files in objects: $C1"
		echo "files in meta: $C2"
		echo "rc=1 faelle: $C3"
		echo "leeres image-data-json: $C4"
		echo "leeres image-preview-json: $C5"
	;;
	atomic)
		while true; do {
		# table: objects
		id="$( db_fetch_nextfile_without_sha256 )"	# mark as 'queued'
		log "id: '$id'"
		test -z "$id" && exit 1

		file="$( db_select_file_from_id "$id" )" || exit 1
		log "file: '$file'"

		mime="$( mimetype_get "$file" )"
		sha256="$( sha256_get "$file" )"

		# table: objects + metadata
		# autodeletes 'queued' keyword in sha256
		id="$( db_insert_mime_and_sha256 "$id" "$mime" "$sha256" || log "inserted rc: $?" )"
		[ -z "$id" ] && log "id: '$id'" && exit 0	# metadata already filled

		case "$mime" in
			'image/'*|'audio'/*)
				meta="$(   "metadata_get_${mime%/*}" "$file" )"
				preview="$( "preview_get_${mime%/*}" "$file" )"
				db_insert_meta_and_preview "$sha256" "$meta" "$preview" || \
					log "db_insert_meta_and_preview: rc: $?"
			;;

			*) log "not handled mime: '$mime'" ;;
		esac
		} done
	;;
	test_images)
		find "$ARG1" -type f | while read -r LINE; do {
			MIME="$( mimetype_get "$LINE" )"

			case "$MIME" in
				image/*) $0 mime "$LINE" || exit 1 ;;
			esac
		} done
	;;
	show_images)
		find "$ARG1" -type f | while read -r LINE; do {
			MIME="$( mimetype_get "$LINE" )"
			MIMEPRE="${MIME%/*}"
			MIMESUB="${MIME#*/}"

			case "$MIMEPRE" in
				image) echo "# $LINE" && feh "$LINE" ;;
			esac
		} done
	;;
	mime)
		MIME="$( mimetype_get "$ARG1" )"

		MIMEPRE="${MIME%/*}"	# e.g. image
		MIMESUB="${MIME#*/}"	# e.g. gif
		JSON="$( mktemp )" || exit 1

		log "detected: $MIME (pre: $MIMEPRE sub: $MIMESUB) -> $ARG1" debug

		case "$MIMEPRE" in
			image)
				funcname_meta="metadata_get_${MIMEPRE}"
				funcname_preview="preview_get_${MIMEPRE}"
			;;
			audio)
				funcname_meta="metadata_get_${MIMEPRE}"
				funcname_preview="preview_get_${MIMEPRE}"
			;;
			*)
				funcname_meta="metadata_get_${MIMEPRE}_${MIMESUB}"
				funcname_preview="preview_get_${MIMEPRE}_${MIMESUB}"
			;;
		esac

		# deps: jq
		if LC_ALL=C command -v "$funcname_meta" >/dev/null; then
			RC=0
			SIZE="$( stat --printf="%s" "$ARG1" )"

			echo "{"
			echo "  \"comment\": \"file_metadata\","
			echo "  \"filename\": \"$ARG1\","	# jsonsafe?
			echo "  \"mime\": \"$MIME\","
			echo "  \"debug:6225\": $( magick convert "$ARG1" png:- | wc -c ),"	# https://github.com/ImageMagick/ImageMagick/issues/6225
			echo "  \"size\": $SIZE"
			echo "}"

			log "# file: '$ARG1' => for FILE in '$PLUGINDIR/'*; do . \$FILE; done && $funcname_meta '$ARG1'" debug
			$funcname_meta "$ARG1" >"$JSON" || RC=$?
			echo "# json:meta" && cat "$JSON"
			json_check_or_die "$JSON"

			log "# file: '$ARG1' => for FILE in '$PLUGINDIR/'*; do . \$FILE; done && $funcname_preview '$ARG1'" debug
			$funcname_preview "$ARG1" >"$JSON" || RC=$?
			echo "# json:preview" && cat "$JSON"
			json_check_or_die "$JSON" && rm -f "$JSON"

			test "$RC" = 0
		else
			log "missing: $MIME -> $funcname_meta | $ARG1"
		fi
	;;
	check_deps)
		dependencies_check "$ARG1"
	;;
	check_code)
		check_code
	;;
	check)
		dependencies_check "$ARG1" || exit 1
		check_code || exit 1

		# systemctl status postgresql
		# cat /home/bastian/.pgpass
		#
		# sudo -u postgres createuser bastian
		# sudo -u postgres psql -c 'create database rexxbot;'
		# sudo -u postgres psql -c 'grant all privileges on database rexxbot to bastian;'
		# sudo -u postgres psql -c "alter user bastian with encrypted password 'geheim';"

		# sudo -u postgres psql -c "create schema rexxbot;"
		# sudo -u postgres psql -c "SET search_path TO rexxbot;"

		# sudo -u postgres psql -c 'ALTER DATABASE rexxbot OWNER TO bastian;'
		# sudo -u postgres psql -c 'ALTER SCHEMA rexxbot OWNER TO bastian;'

		# sudo -u postgres psql --dbname=rexxbot -c 'grant usage,create on schema rexxbot to bastian;'
		# sudo -u postgres psql -c 'GRANT ALL ON SCHEMA public TO bastian;'
		# sudo -u postgres psql -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA rexxbot TO bastian;'
		# sudo -u postgres psql -c 'grant all privileges on database rexxbot to bastian;'
		# sudo -u postgres psql -c 'grant usage,create on schema rexxbot to bastian;'

		# psql --quiet -h localhost -U bastian --dbname=rexxbot -P pager=off -c "\l+"	// list databases
		# psql --quiet -h localhost -U bastian --dbname=rexxbot -P pager=off -c "\dn+"	// list schemas => namespaces
	;;
	*)
		usage && false
	;;
esac
